# The name of the welding CDRM file to load.
string cdrm_filename

# The group name for the full planning group.
string planning_group_name

# The group name which controls the robot.
string robot_group_name

# Optional group name for the robot positioner (track).
string robot_positioner_group_name

# The name of the nozzle link (must be syummetrical around Z).
string nozzle_link_name

# The name of the workpiece link (with attached collision meshes).
string workpiece_link_name

# The planning timeout in seconds.
float64 planning_timeout

# Points along the path which make the weld.
geometry_msgs/Point[] weld_points

# Unit vector directions indicating the nominal wire direction.
geometry_msgs/Vector3[] weld_directions

# Welding speed in m/s.
float64 welding_speed

# Weld range parameters
cdrm_welding_msgs/IntervalWithOptimal rx_range
cdrm_welding_msgs/IntervalWithOptimal ry_range
cdrm_welding_msgs/IntervalWithOptimal ctwd_range

---

# Whether a plan was succesfully generated.
bool success

# Planning time taken.
float64 planning_time

# The robot trajectory to weld to part.
moveit_msgs/RobotTrajectory robot_trajectory
