# The location to save the welding CDRM to.
string filename

# The joint model group name to generate.
string group_name

# The group which makes up the end effector.
string end_effector_name

# The name of the nozzle link.
string nozzle_link_name

# The number of vertices in the roadmap.
uint32 nozzle_roadmap_size
uint32 tool_roadmap_size
uint32 robot_roadmap_size

# Number of nearest neighbours to connect to.
uint32 roadmap_k

# The ranges for each parameter to generate.
cdrm_welding_msgs/Interval rx
cdrm_welding_msgs/Interval ry
cdrm_welding_msgs/Interval ctwd

# The resolutions for the various CDRMs
float64 nozzle_resolution
float64 tool_resolution
float64 robot_resolution

---
---
float64 progress
