# The joint model group name to generate.
string group_name

# The TCP and flange link. Note for generation we treat the flange as the contact point.
string tcp_link_name
string flange_link_name

# The number of vertices in the roadmap.
uint32 roadmap_size

# Number of nearest neighbours to connect to.
uint32 roadmap_k

# The workspace mapping resolution.
float64 resolution

# The ranges for each parameter to generate.
cdrm_welding_msgs/Interval rx
cdrm_welding_msgs/Interval ry
cdrm_welding_msgs/Interval ctwd

---
# The min and max distance from the model group origin to a contact.
float64 min_contact_distance
float64 max_contact_distance

# The bounds of the group's workspace.
geometry_msgs/Vector3 workspace_min
geometry_msgs/Vector3 workspace_max
---
float64 progress
