# The location to save the welding CDRM to.
string filename

# The joint model group name to generate.
string group_name

# The TCP link name.
string tcp_link_name

# The name of the flange link.
string flange_link_name

# The group of links which make up the nozzle.
string nozzle_group_name

# The number of vertices in the roadmap.
uint32 roadmap_size

# Number of nearest neighbours to connect to.
uint32 roadmap_k

# The ranges for each parameter to generate.
cdrm_welding_msgs/Interval rx
cdrm_welding_msgs/Interval ry
cdrm_welding_msgs/Interval ctwd

# The resolution in mm for nozzle CDRM.
float64 nozzle_resolution

---
# The min and max distance from the model group origin to a contact.
float64 min_contact_distance
float64 max_contact_distance

# The bounds of the group's workspace.
geometry_msgs/Vector3 workspace_min
geometry_msgs/Vector3 workspace_max
---
float64 progress
