cdrms:
  example_quadruped_leg: example_quadruped.cdrm
planner_configs:
  robot:
    legs:
      al: example_quadruped_leg
      ar: example_quadruped_leg
      bl: example_quadruped_leg
      br: example_quadruped_leg
    range: 0.05
    goal_bias: 0.05
