#!/usr/bin/env bash

rostopic pub cdrm_welding_server/generate_welding_cdrm/goal cdrm_welding_msgs/GenerateWeldingCdrmActionGoal "{ \
  goal: { \
    filename: 'm10ia_on_gantry.welding-cdrm', \
    group_name: robot_with_gantry, \
    end_effector_name: welding_torch, \
    nozzle_link_name: nozzle_link, \
    roadmap_size: 1000, \
    roadmap_k: 10, \
    rx: { min: -0.261799, max: 0.261799 }, \
    ry: { min: -0.610865, max: 0.610865 }, \
    ctwd: { min: 0, max: 0.01 }, \
    nozzle_resolution: 0.001 \
  } \
}"
